### ISSUE TITLE
scroll only work after refresh. scroll doesn't work after cancel the mailing list.

### ISSUE THREAD

**Issue by larissazhu123** [hackher413/hackher413.github.io#67]
scroll only works after refreshing the page. I think the scrolling doesn't work when/after canceling the subscription to mailing list form.

**Comment by ammuiyer** [comment]
Good point, I'll get rid of the mailing list feature since it's outdated anyways

**Comment by ammuiyer** [comment]
Or you can make a PR if you want

**Comment by ammuiyer** [comment]
For now i'm gonna get rid (comment out) the embedded mailchimp code, pending on whether it is necessary, i'll add it in
